[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = [
    "https://i.ytimg.com/vi/Cf1F624tU-s/maxresdefault.jpg",
    "https://i.ytimg.com/vi/AOlkcLtyXkw/maxresdefault.jpg",
    "https://thepythoncode.com/media/articles/fullstack-notes-app-with-fastapi-and-reactjs/Notes_App-min.gif",
    "https://wallpapers.com/images/hd/programming-hd-nutnj7cgiprbs1j2.jpg",
    "https://source.unsplash.com/random/1920x1080/?tech,dark,code"
  ]

[[plugins]]
  package = "@netlify/plugin-sitemap"
